version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: 'recipes_management'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - recipes_management:/var/lib/mysql
      - ./init.sql:/data/application/init.sql

volumes:
  recipes_management: